apiVersion: apps/v1
kind: Deployment  # 资源类型
metadata: #元数据
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
